// quotes.js
window.quotes = [
  "The only limit to our realization of tomorrow is our doubts of today.",
  "The best way to predict the future is to create it.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Believe you can and you're halfway there.",
  "Do what you can, with what you have, where you are.",
  "Your time is limited, don’t waste it living someone else’s life.",
  "The only impossible journey is the one you never begin.",
  "You don't like me. come on, what's wrong with you.",
  "Is killing innocent defense less mosquitoes the first step to become a serial killer ?",
  "Who knows maybe my alter ego is not that fragile.",
  "I'm not immortal yet. My legs still get tired.",
  "I'm not one of those pathetic guy whose world stops spinning because of some girl.",
  "I don't want world to think I'm successful, I want to be successful in my own eyes.",
  "It's better to look guilty than to look impotent.",
  "I can fight for you but compete for you.",
  "I miss you more than I remember you.",
  "You're not interesting enough to be offensive.",
  "You are at once both the quiet and the confusion of my heart.",
  "When someone is in love, they look through rose-tinted glasses. Everything’s wonderful. They transform into a soft teddy bear that’s smiling all the time.",
  "A friend is someone who knows all about and still loves you.",
  "Don't insult my intelligence.",
  "One who deceives will always find someone who allows themselves to be deceived.",
  "Water that is too pure has no fish.",
  "Communist until I get rich, feminist until I get married, Atheist until the plane starts falling.",
  "Forget it Jack it's Chinatown.",
  "Make me an offer I can't refuse.",
  "Unrequited love.",
  "If all you have is a hammer, everything looks like a nail.",
  "Keep your powder dry.",
  "The things that are really important in life have a high price. Rebellion. Liberty. Ideals.",
  "Speak softy and carry a big stick, you will go far.",
  "“Contemplation often makes life miserable. We should act more, think less, and stop watching ourselves live.”",
];
